[Variables]
Scale=1
2412=H

Img.W=3840
Img.H=2160

BlurBackground=1
Background=1
Gradient=1
MainColor=0,0,0

Bin.Step=80
BlurMatrix=70,10

WeatherLocation=Hong Kong
WeatherUnits=Metric
Language=en

LeftGrad.0=4,135,249
LeftGrad.1=37, 203, 244
RightGrad.0=135, 242, 119
RightGrad.1=143, 240, 86
OneGrad.0=255, 59, 48
OneGrad.1=250, 151, 21
TwoGrad.0=249, 138, 20
TwoGrad.1=247, 225, 26
ThreeGrad.0=243, 80, 7
ThreeGrad.1=244, 22, 48
LastGrad.0=9, 191, 119
LastGrad.1=66, 209, 121

Cache.Wallpaper=C:\Users\enhan\Pictures\Graphics\Wallpapers\Material.jpg
